# Generated by Django 2.2.7 on 2019-12-27 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='last_update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
