# Generated by Django 2.2.7 on 2019-12-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_html',
            field=models.CharField(max_length=100),
        ),
    ]
