# Generated by Django 2.2.7 on 2019-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191216_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
