# Generated by Django 2.2.7 on 2019-12-16 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191216_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_project', to='personal_info.ContactInfo'),
        ),
    ]
