# Generated by Django 2.2.7 on 2019-12-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('degree', models.CharField(default='', max_length=256)),
                ('specialization', models.CharField(default='', max_length=256)),
                ('field', models.CharField(max_length=256)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('present_check', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='personal_info.ContactInfo')),
            ],
        ),
    ]
