# Generated by Django 2.2.7 on 2019-12-08 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('zip_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('phone', models.PositiveIntegerField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('first_name', 'email')},
            },
        ),
    ]
