# Generated by Django 2.2.7 on 2019-12-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0002_auto_20191223_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic/%Y%m%d/'),
        ),
    ]
