# Generated by Django 2.2.7 on 2019-12-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0003_auto_20191224_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic/%Y/%m/%d/'),
        ),
    ]
