# Generated by Django 2.2.7 on 2019-12-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_skill', models.TextField()),
                ('tech_skill', models.CharField(max_length=255)),
                ('tech_skill_description', models.TextField()),
                ('version', models.DecimalField(decimal_places=2, max_digits=4)),
                ('last_used', models.CharField(default='', max_length=50)),
                ('experience', models.IntegerField()),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='personal_info.ContactInfo')),
            ],
            options={
                'ordering': ['last_update_date'],
            },
        ),
    ]
