# Generated by Django 2.2.7 on 2019-12-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
